### ISSUE TITLE
AttributeError: 'Qwen2ForCausalLM' object has no attribute 'optimizer' during DRPO training

### ISSUE THREAD

**Issue by Some-random** [huggingface/open-r1#145]
Faced this error when running evaluation with the latest code. The command to replicate: 
`ACCELERATE_LOG_LEVEL=info accelerate launch --config_file recipes/accelerate_configs/zero3.yaml --num_processes=7 src/open_r1/grpo.py --config recipes/qwen/Qwen2.5-1.5B-Instruct/grpo/confg_full.yaml
`

And the error:

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/fsx/users/dongweij/open-r1/src/open_r1/grpo.py", line 237, in <module>
[rank0]:     main(script_args, training_args, model_args)
[rank0]:   File "/fsx/users/dongweij/open-r1/src/open_r1/grpo.py", line 189, in main
[rank0]:     train_result = trainer.train(resume_from_checkpoint=checkpoint)
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/fsx/users/dongweij/miniconda3/envs/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 2175, in train
[rank0]:     return inner_training_loop(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/fsx/users/dongweij/miniconda3/envs/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 2554, in _inner_training_loop
[rank0]:     self._maybe_log_save_evaluate(
[rank0]:   File "/fsx/users/dongweij/miniconda3/envs/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 3027, in _maybe_log_save_evaluate
[rank0]:     metrics = self._evaluate(trial, ignore_keys_for_eval)
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/fsx/users/dongweij/miniconda3/envs/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 2981, in _evaluate
[rank0]:     metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/fsx/users/dongweij/miniconda3/envs/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 4001, in evaluate
[rank0]:     output = eval_loop(
[rank0]:              ^^^^^^^^^^
[rank0]:   File "/fsx/users/dongweij/miniconda3/envs/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 4195, in evaluation_loop
[rank0]:     losses, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
[rank0]:                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/fsx/users/dongweij/miniconda3/envs/openr1/lib/python3.11/site-packages/trl/trainer/grpo_trainer.py", line 538, in prediction_step
[rank0]:     loss = self.compute_loss(model, inputs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/fsx/users/dongweij/miniconda3/envs/openr1/lib/python3.11/site-packages/trl/trainer/grpo_trainer.py", line 390, in compute_loss
[rank0]:     with unwrap_model_for_generation(model, self.accelerator) as unwrapped_model:
[rank0]:   File "/fsx/users/dongweij/miniconda3/envs/openr1/lib/python3.11/contextlib.py", line 137, in __enter__
[rank0]:     return next(self.gen)
[rank0]:            ^^^^^^^^^^^^^^
[rank0]:   File "/fsx/users/dongweij/miniconda3/envs/openr1/lib/python3.11/site-packages/trl/models/utils.py", line 192, in unwrap_model_for_generation
[rank0]:     remove_hooks(model)
[rank0]:   File "/fsx/users/dongweij/miniconda3/envs/openr1/lib/python3.11/site-packages/trl/models/utils.py", line 140, in remove_hooks
[rank0]:     if model.optimizer is not None and hasattr(model.optimizer, "parameter_offload"):
[rank0]:        ^^^^^^^^^^^^^^^
[rank0]:   File "/fsx/users/dongweij/miniconda3/envs/openr1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
[rank0]:     raise AttributeError(
[rank0]: AttributeError: 'Qwen2ForCausalLM' object has no attribute 'optimizer'
```

I really appreciate this effort in reproducing R1, and I understand that this project is complicated still in development. However, I've been experiencing difficulties completing even one epoch of training since I started using this project. Would it be possible to release a stable recipe that can run end-to-end, even with a small model and dataset? This would help users better understand the workflow and facilitate learning.

**Comment by Ethereal-sakura** [comment]
I strongly agree!

**Comment by ctjlewis** [comment]
@qgallouedec, sorry for so many pings, but no idea what to do about this.

**Comment by Andcircle** [comment]
@Some-random any updates on how to solve it? thanks

**Comment by yeshsurya** [comment]
Need to pin , till issue is fixed by trl : 
`trl==0.14.0
transformers==4.48.2`

**Comment by Andcircle** [comment]
@yeshsurya 
Thanks I changed to trl==0.14.0 transformers==4.48.2 version

Then I got error:
q_embed = (q * cos) + (rotate_half(q) * sin)
RuntimeError: The size of tensor a (784) must match the size of tensor b (785) at non-singleton dimension 2

Did little bit search:
It's recommend to change per device training size to 2, I did that:
Then:
Got error:
RuntimeError: The size of tensor a (1143) must match the size of tensor b (1144) at non-singleton dimension 2 at the same place q_embed = (q * cos) + (rotate_half(q) * sin)

So far I can train a 1.5 B model without deepspeed zero3, using zero2 only with vllm, but our intention is to use zero3 and train a 7B model.

**Comment by ibndias** [comment]
> Need to pin , till issue is fixed by trl : `trl==0.14.0 transformers==4.48.2`

Works at first but then error when eval or resuming
```
 Traceback (most recent call last):
16   File "/ws/open-r1/src/open_r1/grpo.py", line 249, in <module>
17     main(script_args, training_args, model_args)
18   File "/ws/open-r1/src/open_r1/grpo.py", line 203, in main
19     train_result = trainer.train(resume_from_checkpoint=checkpoint)
20                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
21   File "/ws/open-r1/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 2162, in train
22     return inner_training_loop(
23            ^^^^^^^^^^^^^^^^^^^^
24   File "/ws/open-r1/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 2598, in _inner_training_loop
25     self._maybe_log_save_evaluate(
26   File "/ws/open-r1/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
27     metrics = self._evaluate(trial, ignore_keys_for_eval)
28               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
29   File "/ws/open-r1/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 3025, in _evaluate
30     metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
31               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
32   File "/ws/open-r1/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 4073, in evaluate
33     output = eval_loop(
34              ^^^^^^^^^^
35   File "/ws/open-r1/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 4267, in evaluation_loop
36     losses, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
37                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
38   File "/ws/open-r1/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 4436, in prediction_step
39     has_labels = False if len(self.label_names) == 0 else all(inputs.get(k) is not None for k in self.label_names)
40                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
41   File "/ws/open-r1/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 4436, in <genexpr>
42     has_labels = False if len(self.label_names) == 0 else all(inputs.get(k) is not None for k in self.label_names)
43                                                               ^^^^^^^^^^
44 AttributeError: 'list' object has no attribute 'get'
```

**Comment by francescotaioli** [comment]
Still getting this issue in ```transformers==4.49.0.dev0``` and ```trl==0.15.0.dev0```. For the ```remove_hooks``` function I added the following lines 
```
optimizer = getattr(model, "optimizer", None)
    if optimizer is None:
        return
``` 
I have now the problem in the ```add_hooks``` function.

**Comment by ytchx1999** [comment]
> > Need to pin , till issue is fixed by trl : `trl==0.14.0 transformers==4.48.2`
> 
> Works at first but then error when eval or resuming
> 
> ```
>  Traceback (most recent call last):
> 16   File "/ws/open-r1/src/open_r1/grpo.py", line 249, in <module>
> 17     main(script_args, training_args, model_args)
> 18   File "/ws/open-r1/src/open_r1/grpo.py", line 203, in main
> 19     train_result = trainer.train(resume_from_checkpoint=checkpoint)
> 20                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 21   File "/ws/open-r1/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 2162, in train
> 22     return inner_training_loop(
> 23            ^^^^^^^^^^^^^^^^^^^^
> 24   File "/ws/open-r1/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 2598, in _inner_training_loop
> 25     self._maybe_log_save_evaluate(
> 26   File "/ws/open-r1/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
> 27     metrics = self._evaluate(trial, ignore_keys_for_eval)
> 28               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 29   File "/ws/open-r1/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 3025, in _evaluate
> 30     metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
> 31               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 32   File "/ws/open-r1/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 4073, in evaluate
> 33     output = eval_loop(
> 34              ^^^^^^^^^^
> 35   File "/ws/open-r1/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 4267, in evaluation_loop
> 36     losses, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
> 37                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 38   File "/ws/open-r1/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 4436, in prediction_step
> 39     has_labels = False if len(self.label_names) == 0 else all(inputs.get(k) is not None for k in self.label_names)
> 40                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 41   File "/ws/open-r1/openr1/lib/python3.11/site-packages/transformers/trainer.py", line 4436, in <genexpr>
> 42     has_labels = False if len(self.label_names) == 0 else all(inputs.get(k) is not None for k in self.label_names)
> 43                                                               ^^^^^^^^^^
> 44 AttributeError: 'list' object has no attribute 'get'
> ```

I face the same problem

**Comment by Henrychur** [comment]
> [@yeshsurya](https://github.com/yeshsurya) Thanks I changed to trl==0.14.0 transformers==4.48.2 version
> 
> Then I got error: q_embed = (q * cos) + (rotate_half(q) * sin) RuntimeError: The size of tensor a (784) must match the size of tensor b (785) at non-singleton dimension 2
> 
> Did little bit search: It's recommend to change per device training size to 2, I did that: Then: Got error: RuntimeError: The size of tensor a (1143) must match the size of tensor b (1144) at non-singleton dimension 2 at the same place q_embed = (q * cos) + (rotate_half(q) * sin)
> 
> So far I can train a 1.5 B model without deepspeed zero3, using zero2 only with vllm, but our intention is to use zero3 and train a 7B model.

I faced the same issue with latest trl and transformers=4.48.2
